@extends('layouts.workspace')
@section('title','Consola de remates')
@section('content')
<section class="card p-4 mb-4"><h2 class="h5">Nuevo remate</h2><form method="POST" action="{{ route('admin.auctions.store') }}" class="row g-3">@csrf<div class="col-md-4"><label>Título<input class="form-control" name="title" maxlength="160" required></label></div><div class="col-md-4"><label>Lote<select class="form-select" name="livestock_batch_id" required>@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->code }}</option>@endforeach</select></label></div><div class="col-md-4"><label>Reserva total COP<input class="form-control" name="reserve" type="number" min="0.01" step="0.01" required></label></div><div><button class="btn btn-success">Crear remate</button></div></form></section>
<p class="text-secondary small">Las pujas se registran por el operador. La consola consulta máximos cada diez segundos; no implica conexión con una plataforma externa de subastas.</p>
@forelse($auctions as $auction)<section class="card p-4 mb-3"><h2 class="h5">{{ $auction->title }} · {{ $auction->batch->code }}</h2><p>Estado: {{ ['draft'=>'Borrador','open'=>'Abierto','awarded'=>'Adjudicado','closed'=>'Cerrado'][$auction->status] }} · Reserva: $ {{ number_format($auction->reserve_cents/100,2,',','.') }}</p><p id="bid-{{ $auction->id }}">Mayor puja: $ {{ number_format(($auction->bids_max_amount_cents ?? 0)/100,2,',','.') }}</p>
@if($auction->status==='draft')<form method="POST" action="{{ route('admin.auctions.open',$auction) }}">@csrf<button class="btn btn-success">Abrir</button></form>@elseif($auction->status==='open')<form method="POST" action="{{ route('admin.auctions.bid',$auction) }}" class="row g-2">@csrf<div class="col-md-5"><select name="client_id" class="form-select" aria-label="Ganadero que puja">@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></div><div class="col-md-4"><input class="form-control" name="amount" type="number" min="0.01" max="1000000000" step="0.01" required aria-label="Valor de la puja COP"></div><div class="col-md-3"><button class="btn btn-success">Registrar puja</button></div></form><form class="mt-3" method="POST" action="{{ route('admin.auctions.close',$auction) }}" onsubmit="return confirm('¿Cerrar y adjudicar a la mayor puja?')">@csrf<button class="btn btn-dark">Martillo: cerrar y adjudicar</button></form>@else<p>Adjudicatario: {{ $auction->winner?->name ?? 'Sin pujas' }}</p>@endif</section>@empty<div class="card p-4">No hay remates.</div>@endforelse
{{ $auctions->links('pagination::bootstrap-5') }}
@endsection
@push('scripts')<script>setInterval(async function(){try{const response=await fetch(@json(route('admin.auctions.snapshot')),{headers:{Accept:'application/json'}});if(!response.ok)return;for(const auction of await response.json()){const node=document.getElementById('bid-'+auction.id);if(node)node.textContent='Mayor puja: $ '+((auction.bids_max_amount_cents||0)/100).toLocaleString('es-CO');}}catch(e){}},10000);</script>@endpush
