@extends('layouts.workspace')
@section('title','Ficha 360° del ganadero')
@section('content')
<section class="card p-4 mb-4"><h2 class="h4">{{ $client->name }}</h2><p>{{ $client->document_number ?: 'Sin documento' }} · {{ $client->municipality }} · {{ $client->email }}</p><p>Predio ICA: {{ $client->ica_registration ?: 'Sin registro' }} · Crédito asignado: $ {{ number_format($client->credit_limit,2,',','.') }} · {{ $client->vip ? 'Cliente VIP' : 'Cliente estándar' }}</p><a class="btn btn-outline-success" href="{{ route('admin.clients.edit',$client) }}">Editar cliente</a></section>
@can('permission','sales.manage')<div class="row g-3 mb-4">@foreach(['Ventas acumuladas'=>$sales->sum('total_cents')/100,'Saldo de cartera'=>($sales->sum('total_cents')-$sales->sum('paid_cents'))/100,'Ticket promedio'=>$sales->count()?$sales->avg('total_cents')/100:0] as $label=>$value)<div class="col-md-4"><article class="card p-4"><div class="text-secondary">{{ $label }}</div><strong class="fs-4">$ {{ number_format($value,2,',','.') }}</strong></article></div>@endforeach</div>@endcan
<section class="card p-4 mb-4"><h2 class="h5">Expediente sanitario y legal</h2><p class="small text-secondary">Archivo privado y revisión interna; no consulta automáticamente registros oficiales.</p><form method="POST" enctype="multipart/form-data" action="{{ route('admin.client-documents.store',$client) }}" class="row g-3">@csrf<div class="col-md-3"><select class="form-select" name="kind" aria-label="Tipo de documento">@foreach(['ruv'=>'RUV aftosa','brucellosis'=>'Brucelosis','tuberculosis'=>'Tuberculosis','fedegan'=>'Cédula ganadera','ica'=>'Predio ICA','other'=>'Otro'] as $k=>$v)<option value="{{ $k }}">{{ $v }}</option>@endforeach</select></div><div class="col-md-3"><input class="form-control" name="reference" maxlength="100" placeholder="Referencia" aria-label="Referencia"></div><div class="col-md-3"><input class="form-control" type="date" name="expires_at" aria-label="Fecha de vencimiento"></div><div class="col-md-3"><input class="form-control" type="file" name="file" accept="application/pdf,image/jpeg,image/png" required aria-label="Archivo hasta 5 MB"></div><div><button class="btn btn-success">Agregar documento</button></div></form>
@foreach($documents as $document)<div class="border-top mt-3 pt-3"><a href="{{ route('admin.client-documents.download',$document) }}">{{ $document->kind }} · {{ $document->reference }}</a><span class="ms-2 small">{{ $document->expires_at?->isPast() ? 'Vencido' : ($document->expires_at?->format('d/m/Y') ?? 'Sin fecha') }}</span><form class="row g-2 mt-1" method="POST" action="{{ route('admin.client-documents.review',$document) }}">@csrf @method('PUT')<div class="col-md-3"><select class="form-select" name="review_status">@foreach(['pending'=>'Pendiente','approved'=>'Revisado y aprobado internamente','rejected'=>'Rechazado'] as $k=>$v)<option value="{{ $k }}" @selected($document->review_status===$k)>{{ $v }}</option>@endforeach</select></div><div class="col-md-6"><input class="form-control" name="review_notes" maxlength="3000" value="{{ $document->review_notes }}" placeholder="Observaciones de revisión"></div><div class="col-md-3"><button class="btn btn-outline-success">Guardar revisión</button></div></form><form class="mt-2" method="POST" action="{{ route('admin.client-documents.destroy',$document) }}" onsubmit="return confirm('¿Eliminar documento?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Eliminar</button></form></div>@endforeach</section>
@if($recommendations->isNotEmpty())<section class="card p-4 mb-4"><h2 class="h5">Venta cruzada por propósito de lotes comprados</h2><p class="small text-secondary">Sugerencias comerciales mediante coincidencia de propósito; no son diagnóstico veterinario ni un servicio AI conectado.</p>@foreach($recommendations as $product)<p>{{ $product->name }} · $ {{ number_format($product->price,2,',','.') }}</p>@endforeach</section>@endif
<section class="card p-4"><h2 class="h5">Historial comercial</h2>@foreach($sales as $sale)<p>Venta {{ $sale->sold_at->format('d/m/Y') }} · {{ $sale->quote->number }} · $ {{ number_format($sale->total_cents/100,2,',','.') }}</p>@endforeach @foreach($quotes as $quote)<p>{{ $quote->number }} · {{ $quote->status }}</p>@endforeach @foreach($activities as $activity)<p>{{ $activity->due_at->format('d/m/Y H:i') }} UTC · {{ $activity->title }} · {{ $activity->status }}</p>@endforeach</section>
@endsection
