<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Catálogo ganadero | CowApp</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">@include('partials.cowapp-stitch-theme')</head><body class="bg-light"><nav class="navbar bg-white border-bottom"><div class="container"><a href="{{ route('home') }}">@include('partials.cowapp-logo',['logoSize'=>90])</a><a class="btn btn-outline-success" href="{{ route('login') }}">Ingresar</a></div></nav><main class="container py-5"><h1 class="fw-bold">Ganadería, productos y servicios</h1><p class="text-secondary">Lotes publicados y solicitudes comerciales.</p>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">@foreach($errors->all() as $e)<div>{{ $e }}</div>@endforeach</div>@endif
<form method="GET" class="row g-2 my-4"><div class="col-md-6"><input class="form-control" name="q" value="{{ $filters['q']??'' }}" placeholder="Código de lote" aria-label="Buscar lote"></div><div class="col-md-4"><select class="form-select" name="purpose" aria-label="Propósito"><option value="">Todos los propósitos</option>@foreach(['cria'=>'Cría','ceba'=>'Ceba','leche'=>'Leche','genetica'=>'Genética'] as $k=>$v)<option value="{{ $k }}" @selected(($filters['purpose']??'')===$k)>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-success">Buscar</button></div></form>
<div class="row g-4">@forelse($batches as $batch)<article class="col-md-6 col-lg-4"><div class="card h-100 overflow-hidden">@if($batch->image_url)<img src="{{ $batch->image_url }}" alt="{{ $batch->code }}" class="card-img-top" style="height:220px;object-fit:cover" loading="lazy">@endif<div class="card-body"><h2 class="h5">{{ $batch->code }}</h2><p>{{ $batch->category->name }} · {{ $batch->head_count }} cabezas · {{ $batch->purpose }}</p><p>Promedio: {{ $batch->average_weight_kg ?? 'Sin peso' }} kg</p>@if($batch->price_per_kg)<strong>$ {{ number_format($batch->price_per_kg,2,',','.') }} / kg</strong>@endif<a class="d-block text-success mt-2" href="#solicitud" onclick="document.getElementById('public-lot').value='{{ $batch->id }}'">Solicitar información</a></div></div></article>@empty<p>No hay lotes publicados para este filtro.</p>@endforelse</div><div class="my-3">{{ $batches->links('pagination::bootstrap-5') }}</div>
<h2 class="h4 mt-5">Productos y servicios</h2><div class="row g-3">@forelse($products as $product)<article class="col-md-4"><div class="card h-100 p-3">@if($product->media?->active && str_starts_with($product->media->mime_type,'image/'))<img src="{{ $product->media->url ?? '/storage/'.$product->media->path }}" alt="{{ $product->name }}" style="height:160px;object-fit:cover" loading="lazy">@endif<h3 class="h5 mt-2">{{ $product->name }}</h3><p>{{ $product->description }}</p><strong>$ {{ number_format($product->price,2,',','.') }}</strong></div></article>@empty<p>No hay productos publicados.</p>@endforelse</div>
@include('partials.portal-blocks',['blocks'=>$blocks])
<section class="card p-4 mt-5" id="solicitud"><h2 class="h4">Consignación o consulta comercial</h2><form class="row g-3" method="POST" action="{{ route('catalog.capture') }}">@csrf
@foreach(['name'=>['Nombre','text'],'email'=>['Correo','email'],'phone'=>['Teléfono','tel'],'farm_name'=>['Predio / finca','text'],'municipality'=>['Municipio','text'],'hectares'=>['Hectáreas','number'],'carrying_capacity'=>['Capacidad UGG/Ha','number'],'budget'=>['Presupuesto COP','number']] as $key=>$field)<div class="col-md-6"><label class="form-label" for="public-{{ $key }}">{{ $field[0] }}</label><input id="public-{{ $key }}" class="form-control" type="{{ $field[1] }}" name="{{ $key }}" value="{{ old($key) }}" @if(in_array($key,['name','email']))required @endif @if($field[1]==='number') min="0" step="0.01" @endif></div>@endforeach
<div class="col-md-6"><label class="form-label">Propósito<select class="form-select" name="purpose" required>@foreach(['cria'=>'Cría','ceba'=>'Ceba','leche'=>'Leche','genetica'=>'Genética'] as $k=>$v)<option value="{{ $k }}" @selected(old('purpose')===$k)>{{ $v }}</option>@endforeach</select></label></div>
<div class="col-md-6"><label class="form-label">Lote de interés<select class="form-select" id="public-lot" name="livestock_batch_id"><option value="">Consignación / consulta general</option>@foreach($batches as $batch)<option value="{{ $batch->id }}">{{ $batch->code }}</option>@endforeach</select></label></div>
<div class="col-12"><label class="form-label">Consulta<textarea class="form-control" name="notes" maxlength="3000">{{ old('notes') }}</textarea></label></div><div class="col-12"><label><input type="checkbox" name="consent" value="1" required> Autorizo el uso de estos datos para atender esta solicitud comercial.</label></div><div><button class="btn btn-success">Enviar solicitud</button></div></form></section>
</main></body></html>
