<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Leads y prospectos | CowApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    @include('partials.cowapp-stitch-theme')
    <style>
        :root{--lead-ink:#020219;--lead-muted:#6B7280;--lead-line:#E2E4E8;--lead-green:#0C820C;--lead-earth:#5A4507;--lead-amber:#D37211;--lead-bg:#F1F1F1}
        body{background:var(--lead-bg);color:var(--lead-ink);min-height:100vh}
        .crm-sidebar{width:260px;background:#fff;border-right:1px solid var(--lead-line);min-height:100vh;position:fixed;inset:0 auto 0 0;z-index:1020;padding:1.2rem;display:flex;flex-direction:column}
        .crm-brand{display:flex;align-items:center;gap:.7rem;text-decoration:none;color:var(--lead-ink);font-weight:800;font-size:1.2rem;padding:.35rem .45rem 1.5rem}.brand-mark{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;color:#fff;background:linear-gradient(135deg,var(--lead-earth),var(--lead-green))}
        .nav-caption{font-size:.66rem;text-transform:uppercase;letter-spacing:.12em;color:#999ca5;font-weight:800;padding:0 .75rem;margin:.7rem 0 .4rem}.crm-nav{display:grid;gap:.25rem}.crm-nav a{padding:.7rem .75rem;border-radius:11px;display:flex;align-items:center;gap:.72rem;color:#555966;text-decoration:none;font-size:.86rem;font-weight:650}.crm-nav a:hover{background:#f4f7f4;color:var(--lead-green)}.crm-nav a.active{background:#e9f5e9;color:var(--lead-green)}.crm-nav i{font-size:1.05rem;width:20px;text-align:center}
        .crm-user{margin-top:auto;border-top:1px solid var(--lead-line);padding-top:1rem;display:flex;align-items:center;gap:.65rem}.avatar{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#e6f4e6;color:var(--lead-green);font-weight:800}
        .crm-main{margin-left:260px;padding:1.5rem 2rem 2.5rem}.surface-card{background:#fff;border:1px solid var(--lead-line);border-radius:16px;box-shadow:0 3px 12px rgba(2,2,25,.025)}.metric-label{font-size:.69rem;letter-spacing:.08em;color:var(--lead-muted);font-weight:800;text-transform:uppercase}.metric-value{font-size:1.7rem;font-weight:800;letter-spacing:-.04em}.metric-icon{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:#f1f2f4;color:var(--lead-green)}
        .form-label{font-size:.8rem;font-weight:700}.form-control,.form-select{border-color:#dedfe4;border-radius:10px;padding:.62rem .75rem}.btn{border-radius:10px;font-weight:700}.lead-avatar{height:40px;width:40px;border-radius:12px;display:grid;place-items:center;background:#edf5ed;color:var(--lead-green);font-weight:800}.badge-source{background:#f2f3f5;color:#505461}.status-new{background:#eef2ff;color:#4338ca}.status-contacted{background:#e0f2fe;color:#075985}.status-qualified{background:#dcfce7;color:#166534}.status-disqualified{background:#f1f1f1;color:#555}
        .table>:not(caption)>*>*{padding:.9rem .8rem;vertical-align:middle}.text-muted{color:var(--lead-muted)!important}
        @media(max-width:991.98px){.crm-sidebar{position:static;width:auto;min-height:0;padding:.6rem 1rem;border:0;border-bottom:1px solid var(--lead-line)}.crm-brand{padding:.3rem}.crm-nav{display:flex;overflow:auto}.crm-nav a{white-space:nowrap}.crm-nav .nav-caption{display:none}.crm-user{display:none}.crm-main{margin-left:0;padding:1.2rem 1rem 2rem}}
    </style>
</head>
<body>
<aside class="crm-sidebar" aria-label="Navegación principal">
    <a class="crm-brand" href="{{ route('dashboard') }}"><span class="brand-mark"><i class="bi bi-cow"></i></span><span>CowApp<small class="d-block text-muted" style="font-size:.62rem;letter-spacing:.12em">CRM GANADERO</small></span></a>
    <div class="nav-caption">CRM comercial</div><nav class="crm-nav">
        <a href="{{ route('dashboard') }}"><i class="bi bi-grid"></i>Panel</a>
        @can('permission','clients.manage')<a href="{{ route('admin.clients.index') }}"><i class="bi bi-people"></i>Clientes ganaderos</a>@endcan
        @can('permission','sales-pipeline.manage')<a href="{{ route('admin.sales-pipeline.index') }}"><i class="bi bi-kanban"></i>Pipeline</a>@endcan
        <a class="active" aria-current="page" href="{{ route('admin.leads.index') }}"><i class="bi bi-person-plus"></i>Leads y prospectos</a>
        <a href="{{ route('admin.livestock-batches.index') }}"><i class="bi bi-boxes"></i>Lotes de ganado</a>
        <a href="{{ route('admin.livestock-categories.index') }}"><i class="bi bi-tags"></i>Categorías</a>
        @can('permission','content.manage')<a href="{{ route('admin.media.index') }}"><i class="bi bi-images"></i>Multimedia</a><a href="{{ route('admin.news.index') }}"><i class="bi bi-newspaper"></i>Noticias</a>@endcan
        @can('viewAny',\App\Models\MailSetting::class)<a href="{{ route('admin.settings.mail.edit') }}"><i class="bi bi-envelope-gear"></i>Correo SMTP</a>@endcan
        @can('viewAny',\App\Models\Role::class)<a href="{{ route('admin.roles.index') }}"><i class="bi bi-shield-lock"></i>Roles y permisos</a>@endcan
    </nav>
    <div class="crm-user"><span class="avatar">{{ strtoupper(mb_substr(auth()->user()->name,0,1)) }}</span><div class="overflow-hidden"><div class="fw-bold small text-truncate">{{ auth()->user()->name }}</div><div class="text-muted" style="font-size:.72rem">Cuenta ganadera</div></div><form class="ms-auto" method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-sm btn-light" aria-label="Cerrar sesión"><i class="bi bi-box-arrow-right"></i></button></form></div>
</aside>
<main class="crm-main">
    <header class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><div class="text-muted small mb-1">CRM comercial <span class="mx-1">/</span> Captación</div><h1 class="h3 fw-bold mb-1">Leads y prospectos</h1><p class="small text-muted mb-0">Registra el origen y organiza el seguimiento de potenciales ganaderos.</p></div><a class="btn btn-success" href="#form-lead"><i class="bi bi-person-plus me-1"></i>Nuevo prospecto</a></header>
    @if(session('success'))<div class="alert alert-success alert-dismissible fade show" role="status">{{ session('success') }}<button class="btn-close" data-bs-dismiss="alert" aria-label="Cerrar"></button></div>@endif
    @if($errors->any())<div class="alert alert-danger" role="alert"><strong>Revisa los datos ingresados.</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="row g-3 mb-4" aria-label="Resumen de prospectos">
        <div class="col-6 col-xl-3"><article class="surface-card p-3 p-lg-4 h-100"><div class="d-flex justify-content-between mb-3"><span class="metric-label">Prospectos del mes</span><span class="metric-icon"><i class="bi bi-people"></i></span></div><div class="metric-value">{{ number_format($metrics['month_total']) }}</div><div class="small text-muted">Captados este mes</div></article></div>
        <div class="col-6 col-xl-3"><article class="surface-card p-3 p-lg-4 h-100"><div class="d-flex justify-content-between mb-3"><span class="metric-label">Desde WhatsApp</span><span class="metric-icon text-success"><i class="bi bi-whatsapp"></i></span></div><div class="metric-value">{{ number_format($metrics['month_whatsapp']) }}</div><div class="small text-muted">Origen registrado este mes</div></article></div>
        <div class="col-6 col-xl-3"><article class="surface-card p-3 p-lg-4 h-100"><div class="d-flex justify-content-between mb-3"><span class="metric-label">Calificados</span><span class="metric-icon" style="color:#0C820C"><i class="bi bi-patch-check"></i></span></div><div class="metric-value">{{ number_format($metrics['qualified_total']) }}</div><div class="small text-muted">En seguimiento de tu cuenta</div></article></div>
        <div class="col-6 col-xl-3"><article class="surface-card p-3 p-lg-4 h-100"><div class="d-flex justify-content-between mb-3"><span class="metric-label">Seguimiento pendiente</span><span class="metric-icon" style="color:#D37211"><i class="bi bi-alarm"></i></span></div><div class="metric-value">{{ number_format($metrics['follow_up_due']) }}</div><div class="small text-muted">Fecha de contacto vencida</div></article></div>
    </section>

    <form method="GET" action="{{ route('admin.leads.index') }}" class="surface-card p-3 mb-4"><div class="row g-2 align-items-end"><div class="col-12 col-lg-6"><label class="form-label" for="q">Buscar prospecto</label><input class="form-control" id="q" name="q" maxlength="100" value="{{ $filters['q'] ?? '' }}" placeholder="Nombre, finca, teléfono o interés ganadero"></div><div class="col-6 col-lg-2"><label class="form-label" for="source">Canal de origen</label><select class="form-select" id="source" name="source"><option value="">Todos</option>@foreach($sources as $key=>$label)<option value="{{ $key }}" @selected(($filters['source'] ?? '')===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-6 col-lg-2"><label class="form-label" for="status">Estado</label><select class="form-select" id="status" name="status"><option value="">Todos</option>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected(($filters['status'] ?? '')===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-12 col-lg-2 d-flex gap-2"><button class="btn btn-dark flex-fill"><i class="bi bi-funnel me-1"></i>Filtrar</button><a class="btn btn-light border" href="{{ route('admin.leads.index') }}" aria-label="Limpiar filtros"><i class="bi bi-x-lg"></i></a></div></div></form>

    <section class="surface-card overflow-hidden mb-4"><div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-2 p-3 p-lg-4 pb-3"><div><h2 class="h5 fw-bold mb-1">Bandeja de prospectos</h2><p class="small text-muted mb-0">{{ number_format($leads->total()) }} registros de tu cuenta</p></div><span class="small text-muted">Ordenados por fecha de seguimiento</span></div>
        <div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Prospecto</th><th>Canal</th><th>Interés ganadero</th><th>Estado</th><th>Seguimiento</th><th class="text-end">Acciones</th></tr></thead><tbody>
            @forelse($leads as $lead)<tr><td><div class="d-flex align-items-center gap-2"><span class="lead-avatar">{{ strtoupper(mb_substr($lead->name,0,1)) }}</span><div class="min-width-0"><div class="fw-bold text-truncate">{{ $lead->name }} <span class="badge bg-light text-success">{{ $lead->score() }}</span></div><div class="small text-muted">{{ $lead->farm_name ?: ($lead->municipality ?: 'Finca no especificada') }}</div>@if($lead->phone)<div class="small text-muted">{{ $lead->phone }}</div>@endif</div></div></td><td><span class="badge rounded-pill badge-source">{{ $sources[$lead->source] }}</span></td><td>{{ $lead->livestock_interest ?: '—' }}@if($lead->estimated_heads)<div class="small text-muted">{{ number_format($lead->estimated_heads) }} cabezas estimadas</div>@endif</td><td><span class="badge rounded-pill status-{{ $lead->status }}">{{ $statuses[$lead->status] }}</span></td><td>{{ $lead->follow_up_at?->format('d/m/Y') ?? '—' }}</td><td class="text-end text-nowrap">@can('permission','clients.manage')@can('permission','sales-pipeline.manage')<form class="d-inline" method="POST" action="{{ route('admin.leads.convert',$lead) }}">@csrf<button class="btn btn-sm btn-outline-success">{{ $lead->converted_opportunity_id ? 'Ver negocio' : 'Convertir a negocio' }}</button></form>@endcan @endcan<a class="btn btn-sm btn-light border" href="{{ route('admin.leads.edit',array_merge(['lead'=>$lead->id],request()->query())) }}" aria-label="Editar {{ $lead->name }}"><i class="bi bi-pencil"></i></a><form class="d-inline" method="POST" action="{{ route('admin.leads.destroy',$lead) }}" onsubmit="return confirm('¿Eliminar este prospecto?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" aria-label="Eliminar {{ $lead->name }}"><i class="bi bi-trash"></i></button></form></td></tr>
            @empty<tr><td colspan="6" class="text-center py-5"><i class="bi bi-person-plus fs-2 text-success"></i><p class="fw-bold mt-2 mb-1">Aún no hay prospectos en esta vista.</p><p class="small text-muted mb-3">Registra un contacto interesado en tus productos ganaderos.</p><a href="#form-lead" class="btn btn-sm btn-success">Registrar prospecto</a></td></tr>@endforelse
        </tbody></table></div><div class="p-3">{{ $leads->links('pagination::bootstrap-5') }}</div>
    </section>

    <section class="surface-card p-3 p-lg-4" id="form-lead"><div class="d-flex justify-content-between align-items-start mb-3"><div><h2 class="h5 fw-bold mb-1">{{ $editingLead ? 'Actualizar prospecto' : 'Registrar prospecto' }}</h2><p class="small text-muted mb-0">Guarda solo la información necesaria para dar seguimiento comercial.</p></div>@if($editingLead)<a class="btn btn-sm btn-light border" href="{{ route('admin.leads.index') }}">Cancelar</a>@endif</div>
        @if($editingLead)<form method="POST" action="{{ route('admin.leads.update',$editingLead) }}">@csrf @method('PUT')@else<form method="POST" action="{{ route('admin.leads.store') }}">@csrf @endif
            <div class="row g-3">
@foreach(['hectares'=>'Hectáreas','carrying_capacity'=>'Capacidad UGG/Ha','budget'=>'Presupuesto COP'] as $key=>$label)<div class="col-md-4"><label for="lead-{{ $key }}" class="form-label">{{ $label }}</label><input id="lead-{{ $key }}" name="{{ $key }}" type="number" class="form-control" min="0" step="0.01" value="{{ old($key,$editingLead?->getAttribute($key)) }}"></div>@endforeach
<div class="col-md-4"><label class="form-label" for="lead-purpose">Propósito</label><select id="lead-purpose" name="purpose" class="form-select"><option value="">Sin definir</option>@foreach(['cria'=>'Cría','ceba'=>'Ceba','leche'=>'Leche','genetica'=>'Genética'] as $key=>$label)<option value="{{ $key }}" @selected(old('purpose',$editingLead?->purpose)===$key)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12"><p class="small text-secondary">Clasificación por capacidad y presupuesto: A1/B1/B2. Es una regla comercial, no evaluación zootécnica automática.</p></div><div class="col-12 col-md-6"><label class="form-label" for="name">Nombre del contacto <span class="text-danger">*</span></label><input class="form-control" id="name" name="name" required maxlength="160" value="{{ old('name',$editingLead?->name) }}">@error('name')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-12 col-md-6"><label class="form-label" for="farm_name">Finca o empresa</label><input class="form-control" id="farm_name" name="farm_name" maxlength="160" value="{{ old('farm_name',$editingLead?->farm_name) }}"></div>
                <div class="col-12 col-md-4"><label class="form-label" for="phone">Teléfono</label><input class="form-control" type="tel" id="phone" name="phone" maxlength="40" value="{{ old('phone',$editingLead?->phone) }}" autocomplete="tel"></div>
                <div class="col-12 col-md-4"><label class="form-label" for="email">Correo electrónico</label><input class="form-control" type="email" id="email" name="email" maxlength="255" value="{{ old('email',$editingLead?->email) }}" autocomplete="email"></div>
                <div class="col-6 col-md-2"><label class="form-label" for="municipality">Municipio</label><input class="form-control" id="municipality" name="municipality" maxlength="100" value="{{ old('municipality',$editingLead?->municipality) }}"></div>
                <div class="col-6 col-md-2"><label class="form-label" for="department">Departamento</label><input class="form-control" id="department" name="department" maxlength="100" value="{{ old('department',$editingLead?->department) }}"></div>
                <div class="col-12 col-md-4"><label class="form-label" for="source-form">Canal de origen <span class="text-danger">*</span></label><select class="form-select" id="source-form" name="source" required>@foreach($sources as $key=>$label)<option value="{{ $key }}" @selected(old('source',$editingLead?->source ?? 'manual')===$key)>{{ $label }}</option>@endforeach</select></div>
                <div class="col-12 col-md-4"><label class="form-label" for="status-form">Estado de seguimiento <span class="text-danger">*</span></label><select class="form-select" id="status-form" name="status" required>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected(old('status',$editingLead?->status ?? 'new')===$key)>{{ $label }}</option>@endforeach</select></div>
                <div class="col-12 col-md-4"><label class="form-label" for="follow_up_at">Próxima fecha de seguimiento</label><input class="form-control" type="date" id="follow_up_at" name="follow_up_at" value="{{ old('follow_up_at',$editingLead?->follow_up_at?->format('Y-m-d')) }}"></div>
                <div class="col-12 col-md-8"><label class="form-label" for="livestock_interest">Interés ganadero</label><input class="form-control" id="livestock_interest" name="livestock_interest" maxlength="200" value="{{ old('livestock_interest',$editingLead?->livestock_interest) }}" placeholder="Raza, categoría o tipo de ganado"></div>
                <div class="col-12 col-md-4"><label class="form-label" for="estimated_heads">Cabezas estimadas</label><input class="form-control" type="number" min="1" max="1000000" id="estimated_heads" name="estimated_heads" value="{{ old('estimated_heads',$editingLead?->estimated_heads) }}"></div>
                <div class="col-12"><label class="form-label" for="notes">Notas del seguimiento</label><textarea class="form-control" id="notes" name="notes" rows="3" maxlength="3000">{{ old('notes',$editingLead?->notes) }}</textarea></div>
                <div class="col-12 d-flex justify-content-end"><button class="btn btn-success px-4"><i class="bi bi-check2 me-1"></i>{{ $editingLead ? 'Guardar cambios' : 'Guardar prospecto' }}</button></div>
            </div>
        </form>
    </section>
    <footer class="small text-muted mt-4">Los prospectos se guardan bajo tu cuenta. El canal WhatsApp indica el origen del contacto; la sincronización externa no está configurada en este módulo.</footer>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
