@extends('layouts.workspace')
@section('title','Cotizaciones, liquidaciones y contratos')
@section('content')
<section class="card p-4 mb-4"><h2 class="h5">{{ $editing ? 'Editar cotización' : 'Nueva liquidación' }}</h2><p class="small text-secondary">Kilos netos = kilos brutos × (1 − merma %). Las deducciones se calculan sobre el subtotal. Configura los valores aplicables a la operación; no se presume una cuota FEDEGÁN sobre compraventa.</p>
<form method="POST" action="{{ $editing ? route('admin.quotes.update',$editing) : route('admin.quotes.store') }}" class="row g-3">@csrf @if($editing)@method('PUT')@endif
<div class="col-md-6"><label class="form-label">Cliente<select class="form-select" name="client_id" required><option value="">Seleccionar</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected(old('client_id',$editing?->client_id)==$client->id)>{{ $client->name }}</option>@endforeach</select></label></div>
<div class="col-md-6"><label class="form-label">Lote (opcional)<select class="form-select" name="livestock_batch_id"><option value="">Sin lote</option>@foreach($batches as $batch)<option value="{{ $batch->id }}" @selected(old('livestock_batch_id',$editing?->livestock_batch_id)==$batch->id)>{{ $batch->code }}</option>@endforeach</select></label></div>
@foreach(['title'=>['Concepto','text',''], 'gross_kg'=>['Kilos brutos','number',0], 'shrink_percent'=>['Merma %','number',0], 'price_per_kg'=>['Precio por kg COP','number',0], 'withholding_percent'=>['Retención aplicable %','number',0], 'commission_percent'=>['Comisión %','number',3], 'other_deduction'=>['Otras deducciones COP','number',0], 'valid_until'=>['Válida hasta','date',today()->addDays(7)->format('Y-m-d')]] as $key=>$field)<div class="col-12 col-md-4"><label class="form-label" for="quote-{{ $key }}">{{ $field[0] }}</label><input id="quote-{{ $key }}" name="{{ $key }}" type="{{ $field[1] }}" class="form-control" @if($field[1]==='number')step="0.001" min="0"@endif value="{{ old($key,$editing?->getAttribute($key) instanceof \DateTimeInterface ? $editing->getAttribute($key)->format('Y-m-d') : ($editing?->getAttribute($key) ?? $field[2])) }}" required></div>@endforeach
<div class="col-12"><label class="form-label" for="terms">Términos del contrato</label><textarea id="terms" name="terms" class="form-control" maxlength="10000" rows="4">{{ old('terms',$editing?->terms) }}</textarea></div><div class="col-12"><button class="btn btn-success">Calcular y guardar</button> <a class="btn btn-outline-secondary" href="{{ route('admin.quotes.index') }}">Cancelar</a></div></form></section>
<section class="card table-responsive"><table class="table mb-0"><thead><tr><th>Número / cliente</th><th>Subtotal</th><th>Neto a pagar</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>@forelse($quotes as $quote)<tr><td>{{ $quote->number }}<div class="small text-secondary">{{ $quote->client->name }}</div></td><td>$ {{ number_format($quote->subtotal_cents/100,2,',','.') }}</td><td>$ {{ number_format($quote->total_cents/100,2,',','.') }}</td><td>{{ ['draft'=>'Borrador','sent'=>'Enviada','accepted'=>'Aceptada'][$quote->status] ?? $quote->status }}</td><td>
@if($quote->status!=='accepted')<a class="btn btn-sm btn-outline-success" href="{{ route('admin.quotes.edit',$quote) }}">Editar</a><form class="d-inline" method="POST" action="{{ route('admin.quotes.send',$quote) }}">@csrf<button class="btn btn-sm btn-success">Enviar contrato por correo</button></form><form class="d-inline" method="POST" action="{{ route('admin.quotes.destroy',$quote) }}" onsubmit="return confirm('¿Eliminar cotización?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Eliminar</button></form>
@else @can('permission','sales.manage')<form method="POST" action="{{ route('admin.quotes.sell',$quote) }}">@csrf<button class="btn btn-sm btn-success">Registrar venta</button></form>@endcan <div class="small text-secondary">Aceptada {{ $quote->accepted_at?->format('d/m/Y H:i') }} UTC</div>@endif
</td></tr>@empty<tr><td colspan="5" class="p-4 text-center">No hay cotizaciones.</td></tr>@endforelse</tbody></table><div class="p-3">{{ $quotes->links('pagination::bootstrap-5') }}</div></section>
@endsection
